# Generated by Django 5.1 on 2024-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_date_filed_alter_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('filed', 'Field'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('Maintanance', 'Maintanance'), ('Faculty', 'Faculty'), ('Women Grievance', 'Women Grievance'), ('Ragging', 'Ragging'), ('Hostel', 'Hostel'), ('Transport', 'Transport'), ('Canteen', 'Canteen'), ('Other', 'Other')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('cst', 'CST'), ('ece', 'ECE'), ('ect', 'ECT'), ('cai', 'CAI'), ('aiml', 'AIML'), ('mech', 'MECH'), ('civil', 'CIVIL'), ('eee', 'EEE'), ('mba', 'MBA'), ('diploma', 'Diploma')], max_length=20),
        ),
    ]
