# Generated by Django 5.1 on 2024-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaint_status_alter_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Filed', 'Field'), ('In progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Filed', max_length=20),
        ),
    ]
