# Generated by Django 5.1.1 on 2024-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='complaint_documents/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supporting_photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Filed', 'Filed'), ('In progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Filed', max_length=20),
        ),
    ]
